name: turf2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  animated_bottom_navigation_bar: ^1.3.3
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  url_launcher: ^6.3.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.5.3
  google_places_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/Logo.png"

flutter:
  assets:
    - assets/
    - assets/BG.jpg
    - assets/Logo.png
    - assets/football.jpg
    - assets/cricket.jpg
    - assets/hockey.jpg
    - assets/badminton.jpg
    - assets/basketball.jpg
    - assets/tennis.jpg
    - assets/123.jpg
    - assets/search.jpg
    - assets/qr.jpg
    - assets/12.jpg
    - assets/whatsapp.png
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png

  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic